* Encoding: UTF-8.
#Table 4 Predicting UJP
    
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN
  /DEPENDENT UnjustUnFair
  /METHOD=ENTER HTR.

#Table 4 Predicting IT/nonIT 
    
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN
  /DEPENDENT TTC
  /METHOD=ENTER HTR UnjustUnFair.

